FROM nginx:alpine

WORKDIR /var/www

CMD ["nginx"]

COPY ./docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/nginx/sites-available/ /etc/nginx/sites-available

COPY ./src/public /var/www/public

EXPOSE 80 443
