apiVersion: v1
kind: Service
metadata:
  name: apache
  namespace: symfony
spec:
  type: NodePort
  selector:
    app: apache
  ports:
  - protocol: TCP
    port: 80
    targetPort:  80
    nodePort: 30001
