apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: #{APP_NAMESPACE}#
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: #{IMAGE_APACHE}#
        imagePullPolicy: Always
        ports:
          - containerPort: 80
      imagePullSecrets:
        - name: regcred
