apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm
  namespace: symfony
  labels:
    app: php-fpm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-fpm
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      containers:
      - name: php-fpms
        image: $IMAGE_PHP_FPM
        imagePullPolicy: Always
        ports:
          - containerPort: 9000
