apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-fpm
      tier: backend
  template:
    metadata:
      labels:
        app: php-fpm
        tier: backend
    spec:
      containers:
      - name: php-fpm
        image: gcr.io/PROJECT_ID_PLACEHOLDER/php-fpm:VERSION_PLACEHOLDER
