name: Build PROD images and do release

on:
  push:
    tags: "r[0-9]+.[0-9]+.[0-9]+"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Build php-fpm image
        run: docker build -f ./docker/php-fpm/Dockerfile-test -t php-fpm-for-tests:test .
      - name: Start php-fpm container
        run: docker run -d --name testContainer -v "/home/runner/work/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}/app":"/var/www" php-fpm-for-tests:test
      - name: Prepare container
        run: docker exec testContainer composer install
      - name: Run PHPUnit
        run: docker exec testContainer composer phpunit
      - name: Run PHPStan
        run: docker exec testContainer composer phpstan
      - name: Run ecs
        run: docker exec testContainer composer ecs
  build-prod-images:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Get global variables
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "APACHE_IMG_NAME=${GITHUB_REPOSITORY#*/}-apache" >> $GITHUB_ENV
          echo "PHP_FPM_IMG_NAME=${GITHUB_REPOSITORY#*/}-php-fpm" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build apache image
        run: docker build -f ./docker/apache/Dockerfile-prod -t ghcr.io/${{ github.repository_owner }}/${{ env.APACHE_IMG_NAME }}:${{ env.RELEASE_VERSION }} .
        working-directory: ./
      - name: Build php-fpm image
        run: docker build -f ./docker/php-fpm/Dockerfile-prod -t ghcr.io/${{ github.repository_owner }}/${{ env.PHP_FPM_IMG_NAME }}:${{ env.RELEASE_VERSION }} .
        working-directory: ./
      - name: Push apache image
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ env.APACHE_IMG_NAME }}:${{ env.RELEASE_VERSION }}
      - name: Push php-fpm image
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ env.PHP_FPM_IMG_NAME }}:${{ env.RELEASE_VERSION }}
  release-kubernetes:
    needs: build-prod-images
    runs-on: ubuntu-latest
    steps:
      - name: Get global variables
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "APACHE_IMG_NAME=${GITHUB_REPOSITORY#*/}-apache" >> $GITHUB_ENV
          echo "PHP_FPM_IMG_NAME=${GITHUB_REPOSITORY#*/}-php-fpm" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare yaml files
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["kubernetes/release/*.yaml"]'
        env:
          IMAGE_APACHE: ghcr.io/${{ github.repository_owner }}/${{ env.APACHE_IMG_NAME }}:${{ env.RELEASE_VERSION }}
          IMAGE_PHP_FPM: ghcr.io/${{ github.repository_owner }}/${{ env.PHP_FPM_IMG_NAME }}:${{ env.RELEASE_VERSION }}
      - name: Apply config
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f ./kubernetes/release/
