name: Init Kubernetes cluster

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Create namespace symfony
          uses: steebchen/kubectl@master
          env:
            KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          with:
            args: kubectl create namespace symfony
      - name: Apply configs
          uses: steebchen/kubectl@master
          env:
            KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          with:
            args: apply -f ./kubernetes/init/
